Config = {}

Config.UseTarget = GetConvar('UseTarget', 'false') == 'true' -- Use qb-target interactions (don't change this, go to your server.cfg and add `setr UseTarget true` to use this and just that from true to false or the other way around)

Config.MaxInventoryWeight = 120000 -- Max weight a player can carry (default 120kg, written in grams)
Config.MaxInventorySlots = 40 -- Max inventory slots for a player

Config.KeyBinds = {
    Inventory = 'TAB',
    HotBar = 'z'
}

Config.CleanupDropTime = 15 * 60 -- How many seconds it takes for drops to be untouched before being deleted
Config.MaxDropViewDistance = 12.5 -- The distance in GTA Units that a drop can be seen
Config.UseItemDrop = true -- This will enable item object to spawn on drops instead of markers
Config.ItemDropObject = `prop_nigel_bag_pickup` -- if Config.UseItemDrop is true, this will be the prop that spawns for the item

Config.VendingObjects = {
    "prop_vend_soda_01",
    "prop_vend_soda_02",
    "prop_vend_water_01",
	"prop_vend_coffe_01",
}

Config.BinObjects = {
    "prop_bin_05a",
}

Config.CraftingObject = `prop_toolchest_05`

Config.VendingItem = {
    [1] = {
        name = "kurkakola",
        price = 2,
        amount = 50,
        info = {},
        type = "item",
        slot = 1,
    },
    [2] = {
        name = "water_bottle",
        price = 1,
        amount = 50,
        info = {},
        type = "item",
        slot = 2,
    },
}

Config.CraftingItems = {
    [1] = {
        name = "metalscrap1",
        amount = 50,
        info = {},
        costs = {
            ["metalscrap"] = 100,
        },
        type = "item",
        slot = 1,
        threshold = 0,
        points = 1,
    },
    [2] = {
        name = "plastic1",
        amount = 50,
        info = {},
        costs = {
            ["plastic"] = 100,
        },
        type = "item",
        slot = 2,
        threshold = 0,
        points = 1,
    },
    [3] = {
        name = "copper1",
        amount = 50,
        info = {},
        costs = {
            ["copper"] = 100,
        },
        type = "item",
        slot = 3,
        threshold = 0,
        points = 1,
    },
    [4] = {
        name = "aluminum1",
        amount = 50,
        info = {},
        costs = {
            ["aluminum"] = 100,
        },
        type = "item",
        slot = 4,
        threshold = 0,
        points = 1,
    },
    [5] = {
        name = "iron1",
        amount = 50,
        info = {},
        costs = {
            ["iron"] = 100,
        },
        type = "item",
        slot = 5,
        threshold = 0,
        points = 1,
    },
    [6] = {
        name = "steel1",
        amount = 50,
        info = {},
        costs = {
            ["steel"] = 100,
        },
        type = "item",
        slot = 6,
        threshold = 0,
        points = 1,
    },
    [7] = {
        name = "rubber1",
        amount = 50,
        info = {},
        costs = {
            ["rubber"] = 100,
        },
        type = "item",
        slot = 7,
        threshold = 0,
        points = 1,
    },
    [8] = {
        name = "glass1",
        amount = 50,
        info = {},
        costs = {
            ["glass"] = 100,
        },
        type = "item",
        slot = 8,
        threshold = 0,
        points = 1,
    },
	[9] = {
        name = "lockpick",
        amount = 50,
        info = {},
        costs = {
            ["metalscrap"] = 22,
            ["plastic"] = 32,
        },
        type = "item",
        slot = 9,
        threshold = 0,
        points = 1,
    },
    [10] = {
        name = "screwdriverset",
        amount = 50,
        info = {},
        costs = {
            ["metalscrap"] = 30,
            ["plastic"] = 42,
        },
        type = "item",
        slot = 10,
        threshold = 0,
        points = 2,
    },
    [11] = {
        name = "electronickit",
        amount = 50,
        info = {},
        costs = {
            ["metalscrap"] = 30,
            ["plastic"] = 45,
            ["aluminum"] = 28,
        },
        type = "item",
        slot = 11,
        threshold = 0,
        points = 3,
    },
    [12] = {
        name = "radioscanner",
        amount = 50,
        info = {},
        costs = {
            ["electronickit"] = 2,
            ["plastic"] = 52,
            ["steel"] = 40,
        },
        type = "item",
        slot = 12,
        threshold = 0,
        points = 4,
    },	
    [13] = {
        name = "gatecrack",
        amount = 50,
        info = {},
        costs = {
            ["metalscrap"] = 10,
            ["plastic"] = 50,
            ["aluminum"] = 30,
            ["iron"] = 17,
            ["electronickit"] = 1,
        },
        type = "item",
        slot = 13,
        threshold = 0,
        points = 5,
    },
	[14] = {
        name = "boostingdisabler",
        amount = 50,
        info = {},
        costs = {
            ["metalscrap"] = 30,
            ["plastic"] = 23,
            ["aluminum"] = 28,
			["copper"] = 10,
			["rubber"] = 25,
        },
        type = "item",
        slot = 14,
        threshold = 0,
        points = 6,
    },
    [15] = {
        name = "handcuffs",
        amount = 50,
        info = {},
        costs = {
            ["metalscrap"] = 36,
            ["steel"] = 24,
            ["aluminum"] = 28,
        },
        type = "item",
        slot = 15,
        threshold = 160,
        points = 6,
    },
    [16] = {
        name = "repairkit",
        amount = 50,
        info = {},
        costs = {
            ["metalscrap"] = 32,
            ["steel"] = 43,
            ["plastic"] = 61,
        },
        type = "item",
        slot = 16,
        threshold = 200,
        points = 7,
    },
    [17] = {
        name = "pistol_ammo",
        amount = 50,
        info = {},
        costs = {
            ["metalscrap"] = 50,
            ["steel"] = 37,
            ["copper"] = 26,
        },
        type = "item",
        slot = 17,
        threshold = 250,
        points = 8,
    },
    [18] = {
        name = "ironoxide",
        amount = 50,
        info = {},
        costs = {
            ["iron"] = 60,
            ["glass"] = 30,
        },
        type = "item",
        slot = 18,
        threshold = 300,
        points = 9,
    },
    [19] = {
        name = "aluminumoxide",
        amount = 50,
        info = {},
        costs = {
            ["aluminum"] = 60,
            ["glass"] = 30,
        },
        type = "item",
        slot = 19,
        threshold = 300,
        points = 10,
    },
    [20] = {
        name = "armor",
        amount = 50,
        info = {},
        costs = {
            ["iron"] = 33,
            ["steel"] = 44,
            ["plastic"] = 55,
            ["aluminum"] = 22,
        },
        type = "item",
        slot = 20,
        threshold = 350,
        points = 11,
    },
    [21] = {
        name = "drill",
        amount = 50,
        info = {},
        costs = {
            ["iron"] = 50,
            ["steel"] = 50,
            ["screwdriverset"] = 3,
            ["advancedlockpick"] = 2,
        },
        type = "item",
        slot = 21,
        threshold = 400,
        points = 12,
    },
	[22] = {
        name = "snspistol_part_1",
        amount = 50,
        info = {},
        costs = {
            ["iron1"] = 8,
            ["plastic1"] = 8,
            ["copper1"] = 8,
        },
        type = "item",
        slot = 22,
        threshold = 550,
        points = 5,
    },
	[23] = {
        name = "snspistol_part_3",
        amount = 50,
        info = {},
        costs = {
            ["metalscrap1"] = 8,
            ["steel1"] = 8,
        },
        type = "item",
        slot = 23,
        threshold = 550,
        points = 5,
    },
	[24] = {
        name = "vintagepistolhand",
        amount = 50,
        info = {},
        costs = {
            ["iron1"] = 10,
            ["plastic1"] = 10,
            ["copper1"] = 10,
        },
        type = "item",
        slot = 24,
        threshold = 600,
        points = 5,
    },
	[25] = {
        name = "vintagepistolloop",
        amount = 50,
        info = {},
        costs = {
            ["metalscrap1"] = 10,
            ["steel1"] = 10,
        },
        type = "item",
        slot = 25,
        threshold = 600,
        points = 5,
    },
	[26] = {
        name = "berettahandvat",
        amount = 50,
        info = {},
        costs = {
            ["iron1"] = 14,
            ["plastic1"] = 14,
            ["copper1"] = 14,
        },
        type = "item",
        slot = 26,
        threshold = 650,
        points = 5,
    },
	[27] = {
        name = "berettaloop",
        amount = 50,
        info = {},
        costs = {
            ["metalscrap1"] = 14,
            ["steel1"] = 14,
        },
        type = "item",
        slot = 27,
        threshold = 650,
        points = 5,
    },
	[28] = {
        name = "machinepistolhand",
        amount = 50,
        info = {},
        costs = {
            ["iron1"] = 18,
            ["plastic1"] = 18,
            ["copper1"] = 18,
        },
        type = "item",
        slot = 28,
        threshold = 700,
        points = 5,
    },
	[29] = {
        name = "machinepistolloop",
        amount = 50,
        info = {},
        costs = {
            ["metalscrap1"] = 18,
            ["steel1"] = 18,
        },
        type = "item",
        slot = 29,
        threshold = 700,
        points = 5,
    },
	[30] = {
        name = "machinepistolmag",
        amount = 50,
        info = {},
        costs = {
            ["metalscrap1"] = 18,
            ["aluminum1"] = 18
        },
        type = "item",
        slot = 30,
        threshold = 700,
        points = 5,
    },
	[31] = {
        name = "minismghand",
        amount = 50,
        info = {},
        costs = {
            ["iron1"] = 20,
            ["plastic1"] = 20,
            ["copper1"] = 20,
        },
        type = "item",
        slot = 31,
        threshold = 750,
        points = 5,
    },
	[32] = {
        name = "minismgloop",
        amount = 50,
        info = {},
        costs = {
            ["metalscrap1"] = 20,
            ["steel1"] = 20,
        },
        type = "item",
        slot = 32,
        threshold = 750,
        points = 5,
    },
	[33] = {
        name = "minismgmag",
        amount = 50,
        info = {},
        costs = {
            ["iron1"] = 20,
            ["aluminum1"] = 20,
        },
        type = "item",
        slot = 33,
        threshold = 750,
        points = 5,
    },
	[34] = {
        name = "compactriflhandvat",
        amount = 50,
        info = {},
        costs = {
            ["iron1"] = 25,
            ["plastic1"] = 25,
            ["copper1"] = 25,
        },
        type = "item",
        slot = 34,
        threshold = 850,
        points = 5,
    },
	[35] = {
        name = "compactrifleloop",
        amount = 50,
        info = {},
        costs = {
            ["metalscrap1"] = 25,
            ["steel1"] = 25,
        },
        type = "item",
        slot = 35,
        threshold = 850,
        points = 5,
    },
	[36] = {
        name = "compactriflemagazijn",
        amount = 50,
        info = {},
        costs = {
            ["iron1"] = 25,
            ["aluminum1"] = 25,	
        },
        type = "item",
        slot = 36,
        threshold = 850,
        points = 5,
    },
	[37] = {
        name = "smg_ammo",
        amount = 50,
        info = {},
        costs = {
            ["metalscrap1"] = 1,
            ["steel1"] = 1,
            ["copper1"] = 1,
        },
        type = "item",
        slot = 37,
        threshold = 850,
        points = 8,
    },
	[38] = {
        name = "rifle_ammo",
        amount = 50,
        info = {},
        costs = {
            ["metalscrap1"] = 1,
            ["steel1"] = 1,
            ["copper1"] = 1,
			["metalscrap"] = 15,
            ["steel"] = 30,
            ["copper"] = 40,
        },
        type = "item",
        slot = 38,
        threshold = 900,
        points = 8,
    },
}

Config.AttachmentCraftingLocation = vector3(88.91, 3743.88, 40.77)

Config.AttachmentCrafting = {
    ["items"] = {
        [1] = {
            name = "pistol_extendedclip",
            amount = 50,
            info = {},
            costs = {
                ["metalscrap"] = 140,
                ["steel"] = 250,
                ["rubber"] = 60,
            },
            type = "item",
            slot = 1,
            threshold = 0,
            points = 1,
        },
        [2] = {
            name = "pistol_suppressor",
            amount = 50,
            info = {},
            costs = {
                ["metalscrap"] = 165,
                ["steel"] = 285,
                ["rubber"] = 75,
            },
            type = "item",
            slot = 2,
            threshold = 10,
            points = 2,
        },
        [3] = {
            name = "smg_extendedclip",
            amount = 50,
            info = {},
            costs = {
                ["metalscrap"] = 190,
                ["steel"] = 305,
                ["rubber"] = 85,
            },
            type = "item",
            slot = 3,
            threshold = 25,
            points = 3,
        },
        [4] = {
            name = "microsmg_extendedclip",
            amount = 50,
            info = {},
            costs = {
                ["metalscrap"] = 205,
                ["steel"] = 340,
                ["rubber"] = 110,
            },
            type = "item",
            slot = 4,
            threshold = 50,
            points = 4,
        },
        [5] = {
            name = "smg_drum",
            amount = 50,
            info = {},
            costs = {
                ["metalscrap"] = 230,
                ["steel"] = 365,
                ["rubber"] = 130,
            },
            type = "item",
            slot = 5,
            threshold = 75,
            points = 5,
        },
        [6] = {
            name = "smg_scope",
            amount = 50,
            info = {},
            costs = {
                ["metalscrap"] = 255,
                ["steel"] = 390,
                ["rubber"] = 145,
            },
            type = "item",
            slot = 6,
            threshold = 100,
            points = 6,
        },
        [7] = {
            name = "assaultrifle_extendedclip",
            amount = 50,
            info = {},
            costs = {
                ["metalscrap"] = 270,
                ["steel"] = 435,
                ["rubber"] = 155,
                ["smg_extendedclip"] = 1,
            },
            type = "item",
            slot = 7,
            threshold = 150,
            points = 7,
        },
        [8] = {
            name = "assaultrifle_drum",
            amount = 50,
            info = {},
            costs = {
                ["metalscrap"] = 300,
                ["steel"] = 469,
                ["rubber"] = 170,
                ["smg_extendedclip"] = 2,
            },
            type = "item",
            slot = 8,
            threshold = 200,
            points = 8,
        },
    }
}

BackEngineVehicles = {
    [`ninef`] = true,
    [`adder`] = true,
    [`vagner`] = true,
    [`t20`] = true,
    [`infernus`] = true,
    [`zentorno`] = true,
    [`reaper`] = true,
    [`comet2`] = true,
    [`comet3`] = true,
    [`jester`] = true,
    [`jester2`] = true,
    [`cheetah`] = true,
    [`cheetah2`] = true,
    [`prototipo`] = true,
    [`turismor`] = true,
    [`pfister811`] = true,
    [`ardent`] = true,
    [`nero`] = true,
    [`nero2`] = true,
    [`tempesta`] = true,
    [`vacca`] = true,
    [`bullet`] = true,
    [`osiris`] = true,
    [`entityxf`] = true,
    [`turismo2`] = true,
    [`fmj`] = true,
    [`re7b`] = true,
    [`tyrus`] = true,
    [`italigtb`] = true,
    [`penetrator`] = true,
    [`monroe`] = true,
    [`ninef2`] = true,
    [`stingergt`] = true,
    [`surfer`] = true,
    [`surfer2`] = true,
    [`gp1`] = true,
    [`autarch`] = true,
    [`tyrant`] = true,
    [`f7016`] = true
}

Config.MaximumAmmoValues = {
    ["pistol"] = 250,
    ["smg"] = 250,
    ["shotgun"] = 200,
    ["rifle"] = 250,
}
